---

- name: restart tinc
  service:
    name: tinc
    state: "restarted"
  become: yes
  become_method: sudo

- name: reload tinc
  command: /usr/sbin/tincd --kill HUP
  become: yes
  become_method: sudo
